function out = mocalc(atoms,xyz,totalcharge,options)
    
    % Get Basis Set
    basissetdef = basisread(options.basisset);
    basis = makebasis(atoms,xyz,basissetdef);
    
    % Initialize structure for output, include S, T, Vne, Vee generation
    out = struct(...
                'S',         int_overlap(basis),...
                'T',         int_kinenergy(basis),...
                'Vne',       int_attraction(basis),...
                'Vee',       int_repulsion(basis),...
                'epsilon',   0,...
                'C',         0,...
                'P',         0,...
                'E0',        0,...
                'Etot',      0,...
                'basis',     0);
            
    % Core Hamiltonian
    h = out.T + out.Vne;
    
    
    
    
    

end